CREATE TABLE IF NOT EXISTS PLAYERS
(
	PLAYER_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
	USER_ID INTEGER(10) NOT NULL,
	NAME VARCHAR(32 CHAR) NOT NULL,
	SURNAME VARCHAR(32 CHAR) NOT NULL,
	GENDER VARCHAR(1 CHAR) NOT NULL,
	GUEST VARCHAR(1 CHAR) NOT NULL CHECK (GUEST in ('Y', 'N')),
	CREATION_TIMESTAMP TIMESTAMP
);
COMMENT ON TABLE PLAYERS IS 'All the players of the application, namely guest users and real users (with access credentials).';

CREATE TABLE IF NOT EXISTS ACTIVITIES
(
	ACTIVITY_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
	ACTIVITY_DATE DATE NOT NULL,
	ACTIVITY_TIME TIME,
	DURATION TIME,
	FIRST_PLAYER_ID INTEGER(10),
	SECOND_PLAYER_ID INTEGER(10),
	ACTIVITY_TYPE VARCHAR(16 CHAR) NOT NULL,
	CLUB VARCHAR(128 CHAR),
	TOURNAMENT VARCHAR(128 CHAR),
	NOTES VARCHAR(1024 CHAR),
	CONSTRAINT FIRST_PLAYER_ID_FK FOREIGN KEY (FIRST_PLAYER_ID) REFERENCES PLAYERS (PLAYER_ID),
	CONSTRAINT SECOND_PLAYER_ID_FK FOREIGN KEY (SECOND_PLAYER_ID) REFERENCES PLAYERS (PLAYER_ID)
);
COMMENT ON TABLE ACTIVITIES IS 'The activities performed by all the users.';

CREATE TABLE IF NOT EXISTS RESULTS
(
	ACTIVITY_ID INTEGER(10) PRIMARY KEY,
	"3_OR_5_SETTER" INTEGER(1) NOT NULL CHECK ("3_OR_5_SETTER" in (3, 5)),
	LAST_SET_TIEBREAK VARCHAR(1 CHAR) NOT NULL CHECK (LAST_SET_TIEBREAK in ('Y', 'N')),
	SET_1_P_1 INTEGER,
	SET_1_P_2 INTEGER,
	SET_2_P_1 INTEGER,
	SET_2_P_2 INTEGER,
	SET_3_P_1 INTEGER,
	SET_3_P_2 INTEGER,
	SET_4_P_1 INTEGER,
	SET_4_P_2 INTEGER,
	SET_5_P_1 INTEGER,
	SET_5_P_2 INTEGER,
	CONSTRAINT ACTIVITY_ID_FK FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES (ACTIVITY_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE RESULTS IS 'The results of the matches (for activities that have results).'